### PR TITLE
Add enter, exit terms

### PR DESCRIPTION
**Pull request by wooorm**
Closes GH-24.

### CODE REVIEW

**Comment by wooorm** [comment]
Thanks for checking in!

Yes, I’m going with your last paragraph. I laid the problem out a bit in the issue: I think that adding more back-and-forth references is good.

Although, for the external resource: I can see the glossary becoming rather big, in the future it could be a different project?

**Comment by wooorm** [comment]
(for these terms, it arose because hast has a concept of “spaces” that are automatically toggled when entering and exiting, such as described here: https://github.com/syntax-tree/hast-util-to-parse5#space and in other places)

**Comment by ChristianMurphy** [comment]
> I can see the glossary becoming rather big, in the future it could be a different project?

I was thinking the same thing.
With the amount of similarity between the projects, and the amount of terminology and CS theory behind it.
Having a project to centralize the documentation could be good.

**Comment by wooorm** [comment]
> Having a project to centralize the documentation could be good.

This does align with my goals a) everything is its own module and b) being welcome to other projects!
I, however, do not have a CS degree so I don’t know much about trees other than working on them the last years 😅 

Would this be something like the initial section of the [babel plugin handbook](https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md#babel-plugin-handbook)? Do you have other resources?

**Comment by ChristianMurphy** [comment]
> Would this be something like the initial section of the babel plugin handbook?

Exactly like that.

> Do you have other resources?

[MIT OpenCourseware](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-035-computer-language-engineering-spring-2010), [compiler design books](https://github.com/skylake59/awesome-compilers#introductory) ([more](https://www.google.com/search?q=compiler+design+book+pdf)), [wikipedia](https://en.wikipedia.org/wiki/Abstract_syntax_tree)

**Comment by ChristianMurphy** [comment]
There are also tools for creating and organization larger documentation sites.
https://www.gitbook.com, https://docusaurus.io, [and many more](https://github.com/PharkMillups/beautiful-docs#generating-docs)

**Comment by endiliey** [comment]
A bit random, but we recommend docusaurus 😉 

The next major version (still wip)  https://v2.docusaurus.io/ is powered by MDX (part of unifiedjs)

**Comment by wooorm** [comment]
Moving this discussion to syntax-tree/ideas#7

**Pull request merged**
